### ISSUE TITLE
Rename wrongly named packages

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/fa-db#34]
## Background
Some packages use non-standard names, containing underscores.

## Feature
Rename the packages to follow the naming conventions.
Considering renaming the `DBFunction` successor classes.

## Example [Optional]
`naming_conventions`
`letters_case`

**Comment by lsulak** [comment]
+ let's not forget about https://github.com/AbsaOSS/fa-db/pull/36#pullrequestreview-1472447380
